### ISSUE TITLE
Add ability to show valuation(s) of transfer.

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#28]

**Comment by bobismijnnaam** [comment]
What is a valuation of a transfer?

**Comment by danionita** [comment]
The value of its valuation formula.

**Comment by bobismijnnaam** [comment]
As a tooltip, or label? Maybe a right click menu?

Op 20 aug. 2016 11:48 a.m. schreef "danionita" notifications@github.com:

**Comment by danionita** [comment]
More like a label. The idea is that if I want to print a model or include
one in a document, I have to have a separate table or something showing the
values. Also, if I want to inspect the value of a port or transfer, it
takes 3 clicks to do it, which could be streamlined.

Maybe a button that (temporarily) displays values next to every port?
Anyway, this is not very urgent and more of a nice-to-have. If a per-port
tool tip is much easier, I would settle with that for now.

**Comment by bobismijnnaam** [comment]
Simply implemented since eb3320c87d4f2e1efb589d8cedd1758b15f1c678. Thoughts:

At the moment it's quite hard to make the labels aware of other labels so we need some trick. Maybe listing the valuations per value interface? Or printing them in a small font, covering the value ports? I might be able to position them next to the value port on the value exchange, but that might be overengineering if there's a simpler solution.

We could also special case it. Since most value interfaces only have two value ports, we could exploit that. The left vp would have it s label on the left, and the right vp would have its label on the right. For vi's with more than 2 vp's we would either just lay them out left to right, make only one label (and putting all the valuations in there), or simply turn it off.

Also, obviously the customization plays a role as well. When the user selects a grayscale style, the valuation labels should not be bright green.
