### ISSUE TITLE
Value interfaces attached to value activities should only be connectable to the actors which contain those value activities

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#48]

**Comment by danionita** [comment]
Transfers connected to value interfaces attached to value activities should only be connectable to value interfaces attaches to actors which contain the  respective value activities.

**Comment by bobismijnnaam** [comment]
Alright. Should then a value activity also only be able to exist when it is contained inside an actor, or should it also be able to exist on its own (not being contained by anything). Because then it cannot connect to anything. Or is it so that when a value activity is a top-level element, it can connect to other elements normally, and when it is contained in an actor, it can only connect to containing actors?

**Comment by bobismijnnaam** [comment]
Made a small beginning as of 31f1d46133eb30f651f7966d70820e91efa54f93. Is this the correct way? Atm I treat markets egments as if they are actors.
