### ISSUE TITLE
Pass an extra flag to fraud generation when a model already has colluded actors

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#5]
To prevent the generation phase from generating even more colluded actor groups (which we do not support yet)

**Comment by danionita** [comment]
How would one go about colluding actors in the editor? 
Also, such a feature might require a lot or (re)work.
Therefore, my (temporary) proposal is this: since collusion is semantically identical to merging actors, one can simply create a single actor to represent collusion. Conversely, when a model containing collusion is returned by the e3fraud generator to the editor, simply merge the two actors. Any overlaps can be resolved by the user via drag-and-drop. What do you think?  Would this save us time or are wold we be shooting ourselves in the foot?

**Comment by danionita** [comment]
This is no longer necessary as fraud models can no longer be fed into the fraud generator,
