### ISSUE TITLE
Problem when connecting interface of composite actor to one of its sub actors

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#52]
When connecting the interface of a composite actor to the interface of one of its sub-actors, the port checking semantics have to be reversed: in ports can only be connected to in ports and out ports only to out ports.

**Comment by bobismijnnaam** [comment]
The port behaviour enforced in the editor was revised since this issue was posted. It's not the same as the original editor but it's (somewhat) close. Afaik we want to reproduce the previous editor's behaviour as good as possible, right? How should we proceed with the value port directions and multiplicity of value exchanges? Because the old editor allows basically anything

**Comment by danionita** [comment]
Let's put this on standby and discuss it when I am back.
