### ISSUE TITLE
(do not) Restrict protected attributes

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#68]
The user should not be able to:
- create OCCURRENCES formulas. These are only allowed on StartStimuli.

**Comment by bobismijnnaam** [comment]
So on anything except start stimuli, there should not be an "OCCURRENCES" formula on the object?

**Comment by bobismijnnaam** [comment]
Implemented as of 48562426b6af8495ed45a6c2fba5d16453bf2487. Is this ok?

**Comment by danionita** [comment]
Great! I'll reopen this if I can think of others.

**Comment by danionita** [comment]
For some reason, endStimuli have OCCURRENCES attached to them. OCCURRENCES are only allowed on StartStimuli and Value Interfaces so this creates a deadlock when editing the properties of a endStimuli: one cannot close the window because there is an error thrown about OCCURRENCES being only attachable to startStimuli.

I suggest dropping this constraint to prevent further problems.

**Comment by bobismijnnaam** [comment]
I'm not sure which version you used, but in the version I just pulled the end stimuli don't have occurrences formulas. Did you maybe open an old model? Because it's almost guaranteed that old models still have the occurrences formula set, which breaks the editor. We can either drop this as you suggested or you'll have to doctor your models a bit (by opening them as a zip file and editing the xml file by hand).

Do you still want me to remove this feature? Because I think it's good to let the user know this way they can't have occurrences formulas.

**Comment by danionita** [comment]
Actually the only place I don't want occurrence formulas are value
interfaces. Because they would get overwritten by the profitability
computation. I think we should either only restrict value interfaces or
none at all.
