### ISSUE TITLE
When opening a fraud model from the fraud generation module, hidden transfers do not receive IDs

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#76]

**Comment by bobismijnnaam** [comment]
If I open the default flat rate telephony example, do some fraud generation, open one with a hidden transaction, open it in the editor, and then inspect the properties of the hidden edge, it has an ID. So I'm not sure if I understand the issue correctly. Moreover, when the properties of this edge are inspected, and the user closes the window, the editor complains about propagation. Should maybe the valuations be propagated immediately after opening the model in the editor? If that is the case I need to edit some code, since this then should not be undo-able in my opinion either.

**Comment by danionita** [comment]
When I tried it yesterday it didn't work, but maybe I did something wrong
or the commit yesterday fixed it.
Anyway, yes the value should be automatically  propagated to ports I think.
Otherwise running a profitability analysis in the generated model will give
weird results.

Best regards,
Dan Ionita

**Comment by bobismijnnaam** [comment]
Huh, ok. Maybe show me next week what you did specifically and what it looked like?

I'll have a look at it and create a new issue.
