### ISSUE TITLE
Passing of models containing MSs to fraud generation

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#77]

**Comment by bobismijnnaam** [comment]
I'll get this in there, should be doable. It'll break some save files though (because I have to add an attribute to MarketSegment.java in the info package). Which is ok for now I guess. Are you sure the logic works out ok? Isn't it kind of weird if an actor colludes with a market segment (which means it's colluding with hundred other actors?)? Oh well :p

**Comment by bobismijnnaam** [comment]
I think I'm almost done implementing this. What should the RDF.type be of a colluded actor that is both a market segment and an actor? It can't be both since the RDF doesn't allow that 😞

**Comment by bobismijnnaam** [comment]
It should be implemented now, but untested.

**Comment by danionita** [comment]
Somehow I did not consider this. We might have opened a can of worms by
allowing this... Other questions come to mind such as what to do with the
COUNT attribute of the MS and how to compute the result of a colluded actor
- ms.

I'll have a look on Monday and try to come up with some answers :)

Best regards,
Dan Ionita

On Oct 15, 2016 3:28 PM, "Bob Rubbens" notifications@github.com wrote:

I think I'm almost done implementing this. What should the RDF.type be of a
colluded actor that is both a market segment and an actor? It can't be both
since the RDF doesn't allow that 😞

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/danionita/e3tools/issues/77#issuecomment-253984298,
or mute
the thread

**Comment by bobismijnnaam** [comment]
I think that it should be possible, since a marketsegment is just many actors, so conceptually an actor should be able to merge with a market segment/100 actors. Not sure what the implications are on your fraud calculation though. If needed I can multiply every market segment formula by the COUNT formula before merging them into the colluded actor? But that might not be the right approach for this.

**Comment by danionita** [comment]
AFter much deliberation we decided not to allow collusion between market segments...
This means:
- there should be n collusion option in the context menu of Market Segments
- When a model containing market segments is sent to fraud generation, a warning should appear asking if all Market Segments should be cast to actors.

**Comment by bobismijnnaam** [comment]
What does the casting to actors mean? That it's `RDF.type` is set to `E3value.actor` instead of `E3value.market_segment`?

**Comment by danionita** [comment]
Yes. And it should be a yes/no dialog, where yes sends the converted model to fraud generation while no sends the unchanged model (containing MSs).

**Comment by bobismijnnaam** [comment]
recording small discussion:

About issue https://github.com/danionita/e3tools/issues/77  . When I cast a market segment to an actor, do I also take the COUNT variable into account? So if an MS has COUNT 100, do I add 100 actors or something? Or just one actor if the user wants to cast?
GitHub
Passing of models containing MSs to fraud generation · Issue #77 · danionita/e3tools · GitHub
e3tools - e3tool is a Java GUI-based tool for constructing and evaluating e3value models. Includes the e3fraud fraud assessment extension
 

[9:49]  
(one actor with COUNT 100, it is then)

dan [9:55 AM] 
Nope, ignore the COUNT

[9:55]  
You can even leave it there.

**Comment by bobismijnnaam** [comment]
Works as of 716f90e2e4d7b5f836979947271ee3328b3cee5b
