### ISSUE TITLE
Allow connecting Value Activities to one another.

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#85]

**Comment by bobismijnnaam** [comment]
I'm not sure if that's a good idea. I remember that after some discussions with you and Jaap, it was decided that value activities can only connect to their "containing" entities. So if you have a VA within an MS/AC it can only connect to the MS or AC it is residing in. If you have a top-level VA it can connect to anything. There's also a comment stating specifically this. Did I interpret our discussions wrong or is this the way it should be?

**Comment by danionita** [comment]
I cannot come up with any reason not to allow it. Do you remember where
that comment was?

There are at least two  reasons to allow it:

   - Figure 5 in the attached paper
   - The old tool allows it

**Comment by bobismijnnaam** [comment]
Do you mean this figure?

![image](https://cloud.githubusercontent.com/assets/3082344/21640933/c2997d66-d278-11e6-9b2d-6528b3b4d029.png)

I see only one value activity in that graph. Anyway, I think the reason why I thought that was because of #48. However #48 does not exclude value activities connecting with eachother, so we should probably allow that. I'll try implementing it today.

**Comment by bobismijnnaam** [comment]
Should work as of d4366c59959368716bd5564e0ca07eaa9cce5969.

**Comment by bobismijnnaam** [comment]
38cf8835299b25b445f49ad27c4704358eed2780 whoops.
