### ISSUE TITLE
Names sometimes overlap element edge

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#86]
1.  Labels of MSs overlap the edge, suggest moving them
![image](https://cloud.githubusercontent.com/assets/11060388/20562551/734e490e-b184-11e6-95e2-bb93d10c5791.png)

1. Labels on both MSs and Actors do not wrap
![image](https://cloud.githubusercontent.com/assets/11060388/20562642/e4794af2-b184-11e6-8338-d48fe5b57d82.png)

1. Labels on MSs and Actors cannot be moved.

**Comment by bobismijnnaam** [comment]
1. I was unable to reproduce this - how did you get to the point that the text went out of the box (what steps are needed to produce this situation)? When I just type for a bit or change the font size it stays inside reasonable bounds.

2. Fixed as of 160fc8fedcfb6dc7ffca5e6aebe21e1ea7a8b87d.

3. Possible as of 25c52743d86ef136dad2dc51d50ad967741c6e29. This does bring about the interesting complication that if an entity has a very long name, but the entity itself is very small, and the label is outside the entity, then the label is still wrapped (which is weird - why would it be wrapped if it's outside the entity :p). I don't think this is a problem since it's an unusual situation, but it's weird nonetheless.

**Comment by danionita** [comment]
1. No text resize needed. Simply create e new MS and enlarge and/or change the aspect ratio of the shape.

**Comment by bobismijnnaam** [comment]
Is 1. fixed with 3.?

**Comment by danionita** [comment]
I guess so.
